stagelopen/core/views.py
from flask import render_template,request,Blueprint


core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''
    
    return render_template('index.html')

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

stagelopen/stage/views.py
from flask import render_template,url_for,flash, redirect,request,Blueprint
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from stagelopen import db
from stagelopen.models import Stage, Interesting
from functools import wraps
from flask import abort
from stagelopen.stage.forms import AddForm, UpdateForm, DeleteForm, ApplyForm





def roles_required(*roles):
    def wrapper(fn):
        @wraps(fn)
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated:
                return redirect(url_for('users.login'))
            if current_user.role not in roles:
                return abort(404)
            return fn(*args, **kwargs)
        return decorated_view
    return wrapper

stage = Blueprint('stage', __name__)

@stage.route('/begeleider')
@roles_required('begeleider')
def begeleider_route():
    return render_template('begeleider.html')


@stage.route('/add_stage', methods=['GET', 'POST'])
@roles_required('begeleider')
def add_stage():
    form = AddForm()
    if form.validate_on_submit():
        student_id = form.student_id.data
        instelling_id = form.instelling_id.data
        begeleider_id = form.begeleider_id.data
        cijfer = form.cijfer.data
        periode = form.periode.data
        new_stage = Stage(student_id=student_id, instelling_id=instelling_id, begeleider_id=begeleider_id, cijfer=cijfer, periode=periode)
        print(new_stage)
        db.session.add(new_stage)
        db.session.commit()
        flash('Stage added successfully')
        return redirect(url_for('users.dashboard'))

    return render_template('add_stage.html', form=form)



@stage.route('/edit_stage/<int:stage_id>', methods=['GET', 'POST'])
@roles_required('begeleider')
def edit_stage(stage_id):
    stage = Stage.query.get(stage_id)
    if not stage:
        return redirect(url_for('begeleider_route'))
    form = UpdateForm()
    if form.validate_on_submit():
        stage.student_id = form.student_id.data
        stage.instelling_id = form.instelling_id.data
        stage.begeleider_id = form.begeleider_id.data
        stage.cijfer = form.cijfer.data
        stage.periode = form.periode.data
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    form.student_id.data = stage.student_id
    form.instelling_id.data = stage.instelling_id
    form.begeleider_id.data = stage.begeleider_id
    form.cijfer.data = stage.cijfer
    form.periode.data = stage.periode
    return render_template('edit_stage.html', form=form, stage=stage)



@stage.route('/delete_stage/<int:stage_id>', methods=['GET', 'POST'])
@roles_required('begeleider')
def delete_stage(stage_id):
    form = DeleteForm()
    if form.validate_on_submit():
        stage = Stage.query.get(stage_id)
        db.session.delete(stage)
        db.session.commit()
        return redirect(url_for('users.dashboard'))
    return render_template('delete_stage.html', form=form)



@stage.route('/apply', methods=["GET", "POST"])
def apply():
    form = ApplyForm()
    if form.validate_on_submit():
         interests = Interesting(interest=form.interest.data, stage_id='stage.id' )
         db.session.add(interests)
         db.session.commit()
         return redirect(url_for('stage.succes'))
    return render_template('list.html',form=form)


@stage.route('/success')
@roles_required('begeleider')
def success():
    interested = Interesting.query.all()
    return render_template('apply.html',interested=interested)
    

@stage.route('/succes')
def succes():
    return "Bedankt voor uw sollicitatie"

@stage.route('/stage-aanbod',methods=['GET','POST'])
def create_post():
    return render_template('create_post.html')


@stage.route('/contacts')

def contacts():
    return render_template('contacts.html')
    

stagelopen/users/views.py
from flask import Flask, render_template, url_for, flash, redirect, request, Blueprint, session
from flask_login import login_user, current_user, logout_user, login_required
from stagelopen import db
from werkzeug.security import generate_password_hash,check_password_hash
from stagelopen.models import User
from stagelopen.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from stagelopen.users.picture_handler import add_profile_pic
from stagelopen.models import Stage


users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data, role = form.role.data)

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)



@users.route('/')
def index():
    if 'username' in session:
        return redirect(url_for('dashboard'))
    return render_template('index.html')

@users.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
    
        user = User.query.filter_by(email = form.email.data).first()
        if user.check_password(form.password.data) and user is not None:
            login_user(user)
            next = request.args.get('next')
            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)
    return render_template('login.html', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.dashboard'))

@users.route('/dashboard',methods=['GET','POST'])
@login_required
def dashboard():
    role = current_user.role
    if role == "student":
        stages = Stage.query.filter_by(student_id=current_user.email)
        return render_template("student_dashboard.html", stages=stages)
    elif role == "begeleider":
        stages = Stage.query.all()
        return render_template("begeleider.html", stages=stages)
    else:
        return redirect(url_for('core.index'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    
    user = User.query.filter_by(username=username).first_or_404()
    
    return render_template('user_blog_posts.html', user=user)

stagelopen/templates/account.html
{% extends "base.html" %}
{% block content %}

&nbsp
&nbsp
  <div align='center'>
    <br><br>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

stagelopen/templates/add_stage.html
{% extends "base.html" %}
{% block content %}

<div class="container h-100">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6">
          <br><br><br><h1>Add Stage</h1>
  <form method="POST" action="{{ url_for('stage.add_stage') }}">
    {{ form.hidden_tag() }}
    <p>
      {{ form.student_id.label }}<br>
      {{ form.student_id(placeholder='email') }}
    </p>
    <p>
      {{ form.instelling_id.label }}<br>
      {{ form.instelling_id(placeholder='naam instelling') }}
    </p>
    <p>
      {{ form.begeleider_id.label }}<br>
      {{ form.begeleider_id(placeholder='naam begeleider') }}
    </p>
    <p>
      {{ form.cijfer.label }}<br>
      {{ form.cijfer(placeholder='cijfer') }}
    </p>
    <p>
      {{ form.periode.label }}<br>
      {{ form.periode(placeholder='semester, jaar') }}
    </p>
    <p>{{ form.submit }}</p>
  </form>

        

      
{% endblock %}

stagelopen/templates/apply.html
{% extends "base.html" %}
{% block content %}
<div class="container"><br><br><br>
  {% for post in interested %}
  <div class="card" ><br>
<div class="card-body"><p class="card-text">{{ post.interest[:100] }}...</p>
        
      </div>
    </div>
    {% endfor %}
{% endblock %}

stagelopen/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>St@genet</title>
    
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/bootstrap.min.css') }}"  />

    <link rel="stylesheet" type="text/css" href= "{{ url_for('static',filename='styles/custom_styles.css') }}" />
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light fixed-top">
        <div class="container">
          <a class="navbar-brand" href="/">&nbsp St@genet</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{{ url_for('users.index') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('core.info') }}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('stage.create_post') }}">Stage Aanbod</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('stage.contacts') }}">Contacts</a>
              </li>


              {% if current_user.is_authenticated %}
              <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li class="nav-item">
    <a class="nav-link" href="{{ url_for('users.account') }}">Account</a></li>
    <li class="nav-item"></li>
    <a class="nav-link" href="{{ url_for('users.dashboard') }}">Dashboard</a></li>
    
    
    
    {% endif %}
    {% if current_user.is_authenticated and current_user.role == "begeleider" %}
    <li class="nav-item">
    <a class="nav-link" href="{{ url_for('stage.success') }}">Interested</a></li>
    {% endif %}
            </ul>
           
          </div></div>




      



    </nav>
    <header class="page-header gradient">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class=flashes>
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
        
    </header>


<div class="container">
    
      {% block content %}
    
      {% endblock %}
      </div>
  

</body>
</html>


      

stagelopen/templates/begeleider.html
{% extends "base.html" %}
{% block content %}

<body class="text-center h-100">
  

    <div class="container h-100"><br><br>
      <div class="row h-100 justify-content-center align-items-center">
          <div class="col-10 col-md-8 col-lg-6">

&nbsp
&nbsp

<br><h1> Welcome {{ current_user.username }}</h1>
<section>&nbsp
<h2>Stages</h2>



<table class="table">
    <thead>
      <tr>
        <th scope="col">Student</th>
        <th scope="col">Instelling</th>
        <th scope="col">Begeleider</th>
        <th scope="col">Cijfer</th>
        <th scope="col">Periode</th>
      </tr>
    </thead>
    <tbody>
        {% for stage in stages %}
      <tr>
        
        <td>{{ stage.student_id }}</td>
        <td>{{ stage.instelling_id }}</td>
        <td>{{ stage.begeleider_id }}</td>
        <td>{{ stage.cijfer }}</td>
        <td>{{ stage.periode }}</td>
        <td>
<a href="{{ url_for('stage.edit_stage', stage_id=stage.id) }}">Update</a>
&nbsp
&nbsp
<a href="{{ url_for('stage.delete_stage', stage_id=stage.id) }}">Delete</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{{ url_for('stage.add_stage') }}">Nieuwe stage toevoegen</a>
</section>
</div>
      </div>
    </div>
    </body>

  {% endblock %}

stagelopen/templates/contacts.html
{% extends "base.html" %}
{% block content %}

<header>
    <header class="page-header gradient">
        <div class="container pt-5">
            <div class="row align-items-links justify-content-links">
                <div class="col-md-5">
                    <p></p>
                    
                    <h1>Contacts</h1>
                    

                    </p>
                    
                </div>
                
            </div>
        </div>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
            <path 
                fill="#fff" 
                fill-opacity="1" 
                d="M0,64L48,74.7C96,85,192,107,288,122.7C384,139,480,149,576,133.3C672,117,768,75,864,85.3C960,96,1056,160,1152,154.7C1248,149,1344,75,1392,37.3L1440,0L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z">
              </path>
        </svg>
      </header>
</header>
<section class="contacts">
    <div class="row">
        <div class="col-sm-12 mb-3 mb-sm-0 justify-content-center">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title">St@genet <br><br>
                Zernikeplein 11 <br>
                9747 AS Groningen <br>
                T 050 123 4567<br>
                info@stagenet.nl
                <br></h3>
                <br>
                
                <section class="companies">
                    <div class="container text-center">
                        <div class="row g-3 align-items-center justify-content-links">
                            <div class="col-md-1"><img src="./static/facebook.svg" alt="logo facebook" class="img-fluid"></div>
                            <div class="col-md-1"><img src="./static/twitter.svg" alt="logo twitter" class="img-fluid"></div>
                            <div class="col-md-1"><img src="./static/linkedin.svg" alt="linkedin logo" class="img-fluid"></div>
                            <div class="col-md-1"><img src="./static/whatsapp.svg" alt="Whatsapp logo" class="img-fluid"></div>
                                   
                        </div>
                    </div>
                  </section>
              
            </div>
          </div>
        </div>
        
          <div class="gradient">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
                <path fill="#fff" 
                      fill-opacity="1" 
                      d="M0,32L60,58.7C120,85,240,139,360,165.3C480,192,600,192,720,160C840,128,960,64,1080,48C1200,32,1320,64,1380,80L1440,96L1440,0L1380,0C1320,0,1200,0,1080,0C960,0,840,0,720,0C600,0,480,0,360,0C240,0,120,0,60,0L0,0Z">
                </path>
            </svg>
        </div> 
        <section class="companies">
            <div class="container text-center">
                <div class="row g-5 align-items-center justify-content-center">
                    <div class="col-md-2"><img src="./static/hanze.png" alt="logo Hanze hoogeschool" class="img-fluid"></div>
                    <div class="col-md-2"><img src="./static/rijksuniversiteit.png" alt="logo Rijksuniversiteit" class="img-fluid"></div>
                    <div class="col-md-2"><img src="./static/hanzepro.png" alt="HanzePro logo" class="img-fluid"></div>
                           
                </div>
            </div>
          </section>
        


{% endblock %}

stagelopen/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
<form action="{{url_for('users.dashboard')}}" method="POST">
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
</head>
<body>
    
    </nav>
    <h1>Dashboard</h1>
    {% if current_user.is_student %}
    <section>&nbsp
        <br><h2>Stages van {{current_user.username}}</h2>
        <table id="data" class="table table-striped">
            <thead>
                <tr>
                    <th>Instelling</th>
                    <th>Begeleider</th>
                    <th>Cijfer</th>
                    <th>Periode</th>
                </tr>
            </thead>
            <tbody>
                {% for stage in stages %}
                <tr>
                    <td>{{ stage.instelling_id }}</td>
                    <td>{{ stage.begeleider_id }}</td>
                    <td>{{ stage.cijfer }}</td>
                    <td>{{ stage.periode }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
    {% else %}
    <section>&nbsp
        <h2>Stages</h2>
        <table id="data" class="table table-striped">
            <thead>
                <tr>
                    <th>Student</th>
                    <th>Instelling</th>
                    <th>Begeleider</th>
                    <th>Cijfer</th>
                    <th>Periode</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for stage in stages %}
                <tr>
                    <td>{{ stage.student_id }}</td>
                    <td>{{ stage.instelling_id }}</td>
                    <td>{{ stage.begeleider_id }}</td>
                    <td>{{ stage.cijfer }}</td>
                    <td>{{ stage.periode }}</td>
                    <td>
                        <a href="{{ url_for('stage.edit_stage', stage_id=stage.id) }}">Bewerk</a>
                        &nbsp
                        &nbsp
                        <a href="{{ url_for('stage.delete_stage', stage_id=stage.id) }}">Verwijder</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <a href="{{ url_for('stage.add_stage') }}">Voeg een stage toe</a>
  
    </section>
    {% endif %}
</body>
</html>
</form>
</div>

{% endblock %}

stagelopen/templates/delete_stage.html
{% extends "base.html" %}
{% block content %}
<br><br><br>
    <h2>Delete Stage</h2>
     <form method="POST">
        {{ form.hidden_tag() }}
        <br><p>Are you sure you want to delete stage {{student_id}} ?</p>
        
        <div class="col-0.5 btn btn-primary align-items-right">
        {{ form.submit(class="form-control col-2 btn btn-primary align-items-center ", size=2) }}
    </div>
        <a href="{{ url_for('users.dashboard') }}" class="btn btn-sm-secondary">Cancel</a
    </form>

{% endblock %}

stagelopen/templates/edit_stage.html
{% extends 'base.html' %}
{% block content %}
  <br><br><br><h1>Edit Stage</h1>
  <form method="POST" action="{{ url_for('stage.edit_stage', stage_id=stage.id) }}">
    {{ form.hidden_tag() }}
    <p>
      {{ form.student_id.label }}<br>
      {{ form.student_id }}
    </p>
    <p>
      {{ form.instelling_id.label }}<br>
      {{ form.instelling_id }}
    </p>
    <p>
      {{ form.begeleider_id.label }}<br>
      {{ form.begeleider_id }}
    </p>
    <p>
      {{ form.cijfer.label }}<br>
      {{ form.cijfer }}
    </p>
    <p>
      {{ form.periode.label }}<br>
      {{ form.periode }}
    </p>
    <p>{{ form.submit }}</p>
  </form>
{% endblock %}

stagelopen/templates/info.html
{% extends "base.html" %}
{% block content %}
&nbsp
&nbsp
<div class="container">
  <br><br><h1>Informatie over onze webpagina</h1>
  <p>Binnen het HBO-onderwijs spelen stages een belangrijke rol. Het is daarom ook belangrijk om de gegevens van de stages goed vast te leggen. In deze website vindt u veel informatie over verschillende stage plekken binnen de HBO onderwijs.

  </p>
</div>

{% endblock %}

stagelopen/templates/list.html
{% extends "base.html" %}
{% block content %}
&nbsp
<div class="container">
    <br><br><br>
    <form class="form-group" method="POST">
       {{ form.hidden_tag() }}
  
       <div class="form-group">
       {{ form.interest.label(class="form-control-label") }}
       {{ form.interest(class="form-control form-control-lg") }}
       </div>
       <div class="form-group">
        <br>
        
           {{ form.submit(class="btn btn-outline-info") }}
       </div>
    </form>

</div>
{% endblock %}

stagelopen/templates/login.html
{% extends "base.html" %}
{% block content %}
<style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
</style>



    

<body class="text-center h-100">
    &nbsp
    &nbsp
    &nbsp
  
  <div class="container h-100">
      <div class="row h-100 justify-content-center align-items-center">
          <div class="col-10 col-md-8 col-lg-6">
            &nbsp;
<form class="form-signin form-control-sm" method="post">
  <img class="mb-4" src="./static/graduate.svg" alt="" width="72" height="72">
    <h1 class="h3 mb-3 font-weight-normal">Inloggen</h1>
    
<form class="row g-3" method="POST">
  {# This hidden_tag is a CSRF security feature. #}
  {{ form.hidden_tag() }}
  {{form.role.label}} {{form.role() }}
  &nbsp
  <div class="form-group row g-3 align-items-center">
    &nbsp

  {{ form.email.label }} {{ form.email(placeholder='Email') }}</div>
  &nbsp
  <div class="form-group row g-3 align-items-center">
  
  {{ form.password.label }} {{ form.password(placeholder='Password') }}</div>
  &nbsp
  <br>
  <div class="col-3 btn btn-primary align-items-right">
    

  {{ form.submit(class="form-control col-2 btn btn-primary align-items-center ", size=6) }}</div>
  
</form>

{% endblock %}
                

stagelopen/templates/student_dashboard.html
{% extends "base.html" %}
{% block content %}

<body class="text-center h-100">
  

    <div class="container h-100">
      <br><br>
      <div class="row h-100 justify-content-center align-items-center">
          <div class="col-10 col-md-8 col-lg-6">

            &nbsp
            &nbsp
<br><h1> Stages van {{ current_user.username }}</h1>
<section>&nbsp
<h2>Mijn stages</h2>



<table class="table">
    <thead>
      <tr>
        <th scope="col">Instelling</th>
        <th scope="col">Begeleider</th>
        <th scope="col">Cijfer</th>
        <th scope="col">Periode</th>
      </tr>
    </thead>
    <tbody>
      {% for stage in stages %}
      <tr>
          <td>{{ stage.instelling_id }}</td>
          <td>{{ stage.begeleider_id }}</td>
          <td>{{ stage.cijfer }}</td>
          <td>{{ stage.periode }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
</div>
      </div>
    </div>
    </body>

  {% endblock %}

stagelopen/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
    </div>
  </div>


{% endblock content %}